#include <filesystem>
#include <fstream>
#include <iostream>
#include <smake/project_config.hpp>
#include <yaml-cpp/node/node.h>
#include <smake/macros.hpp>

namespace yaml = YAML;

const std::string default_config = std::format(R"(# Generated by Smake {}
# Do not change this value
smkgenver: "{}"

project:
    version: "1.0.0" # Your project's version
    name: "Smayke" # Your project's name and final
                   # binary executable/library name
    language: "cpp" # This can be any of the following
    # and following only:
    # "cpp", "custom"

    dependencies: ["freetype"]

    # Don't modify unless you know
    # what you're doing.
    advanced:
        use_default_linker_phase: true
        regen_every_build: true

src_files:
    - "src/main.cpp"
    - "src/util.cpp"

include_directories:
    - "include"
    - "src/include"

compilation:
    additional_cxx_args: "-Wall"
)", SMAKE__VERSION, SMAKE__VERSION);

void create_example_config(std::string file) {
    std::ofstream f(file);
    if (!f.is_open()) {
        return;
    }
    f << default_config;
    f.close();
    std::cout << "smake: configuration created as " << file << '\n';
}

namespace smake {
    int read_project_config(std::string file) {
        if (!std::filesystem::exists(file)) {
            create_example_config(file);
            return 1;
        }

        return 0;
    }

    static std::string vecutil_join(
        const std::vector<std::string>& vec,
        std::string_view delim,
        size_t start = 0
    ) {
        if (start >= vec.size())
            return {};

        std::string s;
        for (size_t i = start; i < vec.size(); ++i) {
            if (!s.empty())
                s += delim;
            s += vec[i];
        }
        return s;
    }

    
    std::string flatten_path(const std::filesystem::path& p) {
        std::string s;
        for (const auto& part : p) {
            if (!s.empty()) s += '_';
            s += part.string();
        }
        return s;
    }

    std::vector<std::string> generate_project_make(std::string file) {
        yaml::Node f = yaml::LoadFile(file);
        if (f["project"]["language"].as<std::string>() != "cpp") {
            return {};
        }
        if (!f["project"]["advanced"]["regen_every_build"].as<bool>()) {
            return {"__skip_write__"};
        }
        std::vector<std::string> lines;
#define LINE_BREAK lines.push_back("")
        lines.push_back("var CXXC " "\"/usr/bin/clang++\""); // FIXME CPL CXX Compiler
        lines.push_back("var CXX_FLAGS " "\"-std=c++23\"");
        lines.push_back("var BINOUT " "\"{PROJECT_DIRECTORY}/bin\"");
        lines.push_back("var OBJOUT " "\"{PROJECT_DIRECTORY}/.obj\"");
        lines.push_back("var LD \"/usr/bin/ld\"");

        std::vector<std::string> object_files;

        LINE_BREAK;

        {
            int i = 0;
            for (auto &src_file : f["src_files"].as<std::vector<std::string>>()) {
                lines.push_back("var SRC_FILE_" + std::to_string(i) + " " + "\"{PROJECT_DIRECTORY}/" + src_file + "\"");
                ++i;
            }
        }

        LINE_BREAK;

        lines.push_back("task.s checks");
        lines.push_back("exec mkdir -p {BINOUT}");
        lines.push_back("exec mkdir -p {OBJOUT}");
        lines.push_back("task.e");

        LINE_BREAK;

        std::vector<std::string> src_files_comps;
        std::vector<std::string> include_dirs;

        for (auto &inc : f["include_directories"].as<std::vector<std::string>>()) {
            include_dirs.push_back("-I{PROJECT_DIRECTORY}/" + inc);
        }

        {
            int i = 0;
            for (auto &src_file : f["src_files"].as<std::vector<std::string>>()) {
                src_files_comps.push_back("-d comp_src_file_" + std::to_string(i));
                lines.push_back("task.s " "comp_src_file_" + std::to_string(i) + " -d checks");
                std::string obj = flatten_path(src_file) + ".o";
                static std::string includes = vecutil_join(include_dirs, " ");
                lines.push_back("exec " "{CXXC} {CXX_FLAGS} " + includes + " -c {SRC_FILE_" + std::to_string(i) + "} -o {OBJOUT}/" + obj);
                lines.push_back("task.e");
                object_files.push_back("{OBJOUT}/" + obj);
                LINE_BREAK;
                ++i;
            }
        }

        if (f["project"]["advanced"]["use_default_linker_phase"].as<bool>()) {
            std::vector<std::string> deps;
            for (auto &d :  f["project"]["dependencies"].as<std::vector<std::string>>()) {
                deps.push_back("-l" + d);
            }
            lines.push_back("task.s linker_phase " + vecutil_join(src_files_comps, " "));
            lines.push_back("exec {LD} -o {BINOUT}/output /usr/lib/crt1.o /usr/lib/crti.o " + vecutil_join(object_files, " ") + " -lc -lstdc++ " + vecutil_join(deps, " ") + " /usr/lib/crtn.o -dynamic-linker /lib64/ld-linux-x86-64.so.2");
            lines.push_back("task.e");

            LINE_BREAK;
        }

        return lines;
    }
}
